### ISSUE TITLE
Allow users to make their own posts

### ISSUE THREAD

**Issue by hillcrestpaul0719** [wlmac/metropolis#57]

**Comment by MikeVarchola** [comment]
Hello, I would like to contribute on this issue. Can you assign it to me? Also I took a look at your project and I cant sign up to make an account because don't have TDSB email, are there any 'test' credentials ? I am from Slovakia, doing this as part of my studies on Technical University of Kosice. Thanks :)

**Comment by JasonLovesDoggo** [comment]
> Hello, I would like to contribute on this issue. Can you assign it to me? Also I took a look at your project and I cant sign up to make an account because don't have TDSB email, are there any 'test' credentials ? I am from Slovakia, doing this as part of my studies on Technical University of Kosice. Thanks :)

You are able to make an account locally with the createsuperuser command.

**Comment by MikeVarchola** [comment]
Alright, I would like to work on this issue then, assign it to me please.

**Comment by MikeVarchola** [comment]
Please assign this issue to me, thanks.

**Comment by nyiyui** [comment]
Hello, and thank you for trying to contribute!

First of all, I want to let you know that we're doing this as part of a school club, and unfortunately, we can't assign the issue to you and may not be able to accept your patch due to school policies.
However, that doesn't mean you can't work on it - if you do, I'd be happy seeing another fork of this project!

**Comment by JasonLovesDoggo** [comment]
+ the better implementation for this would just be a google form.

**Comment by nyiyui** [comment]
Seems like school policies make it hard to allow any student to post (even with approval from staff, it seems). Unless there's a large incentive, I plan to leave this as is (and people who want to post can join Metropolis anyway).
