### ISSUE TITLE
Allow users to make comments & react to posts

### ISSUE THREAD

**Issue by hillcrestpaul0719** [wlmac/metropolis#58]

**Comment by Dominik26-1** [comment]
Hello, I would like to contribute on this issue. I am student front Technical University of Kosice in Slovakia. I cloned project and ran it locally, but I cannot try a lot of functionality, because I do not have your credentials. Can your please provide me dome developers credentials and if its possible to assign me the story. Thanks

**Comment by JasonLovesDoggo** [comment]
> Hello, I would like to contribute on this issue. I am student from Technical University of Kosice in Slovakia. I cloned project and ran it locally, but I cannot try a lot of functionality, because I do not have your credentials. Can your please provide me dome developers credentials and if its possible to assign me the story. Thanks

Thanks but this issue is actually completed, just was passed over and not closed.
